/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PartnerMatchService } from "../partnerMatch.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PartnerMatchCreateInput } from "./PartnerMatchCreateInput";
import { PartnerMatch } from "./PartnerMatch";
import { PartnerMatchFindManyArgs } from "./PartnerMatchFindManyArgs";
import { PartnerMatchWhereUniqueInput } from "./PartnerMatchWhereUniqueInput";
import { PartnerMatchUpdateInput } from "./PartnerMatchUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PartnerMatchControllerBase {
  constructor(
    protected readonly service: PartnerMatchService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PartnerMatch })
  @nestAccessControl.UseRoles({
    resource: "PartnerMatch",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPartnerMatch(
    @common.Body() data: PartnerMatchCreateInput
  ): Promise<PartnerMatch> {
    return await this.service.createPartnerMatch({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        compatibilityScore: true,
        user1: true,
        user2: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PartnerMatch] })
  @ApiNestedQuery(PartnerMatchFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PartnerMatch",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async partnerMatches(
    @common.Req() request: Request
  ): Promise<PartnerMatch[]> {
    const args = plainToClass(PartnerMatchFindManyArgs, request.query);
    return this.service.partnerMatches({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        compatibilityScore: true,
        user1: true,
        user2: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PartnerMatch })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PartnerMatch",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async partnerMatch(
    @common.Param() params: PartnerMatchWhereUniqueInput
  ): Promise<PartnerMatch | null> {
    const result = await this.service.partnerMatch({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        compatibilityScore: true,
        user1: true,
        user2: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PartnerMatch })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PartnerMatch",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePartnerMatch(
    @common.Param() params: PartnerMatchWhereUniqueInput,
    @common.Body() data: PartnerMatchUpdateInput
  ): Promise<PartnerMatch | null> {
    try {
      return await this.service.updatePartnerMatch({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          compatibilityScore: true,
          user1: true,
          user2: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PartnerMatch })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PartnerMatch",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePartnerMatch(
    @common.Param() params: PartnerMatchWhereUniqueInput
  ): Promise<PartnerMatch | null> {
    try {
      return await this.service.deletePartnerMatch({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          compatibilityScore: true,
          user1: true,
          user2: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
