/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { IdeologyClusterService } from "../ideologyCluster.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { IdeologyClusterCreateInput } from "./IdeologyClusterCreateInput";
import { IdeologyCluster } from "./IdeologyCluster";
import { IdeologyClusterFindManyArgs } from "./IdeologyClusterFindManyArgs";
import { IdeologyClusterWhereUniqueInput } from "./IdeologyClusterWhereUniqueInput";
import { IdeologyClusterUpdateInput } from "./IdeologyClusterUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class IdeologyClusterControllerBase {
  constructor(
    protected readonly service: IdeologyClusterService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: IdeologyCluster })
  @nestAccessControl.UseRoles({
    resource: "IdeologyCluster",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createIdeologyCluster(
    @common.Body() data: IdeologyClusterCreateInput
  ): Promise<IdeologyCluster> {
    return await this.service.createIdeologyCluster({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [IdeologyCluster] })
  @ApiNestedQuery(IdeologyClusterFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "IdeologyCluster",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ideologyClusters(
    @common.Req() request: Request
  ): Promise<IdeologyCluster[]> {
    const args = plainToClass(IdeologyClusterFindManyArgs, request.query);
    return this.service.ideologyClusters({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: IdeologyCluster })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IdeologyCluster",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ideologyCluster(
    @common.Param() params: IdeologyClusterWhereUniqueInput
  ): Promise<IdeologyCluster | null> {
    const result = await this.service.ideologyCluster({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: IdeologyCluster })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IdeologyCluster",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateIdeologyCluster(
    @common.Param() params: IdeologyClusterWhereUniqueInput,
    @common.Body() data: IdeologyClusterUpdateInput
  ): Promise<IdeologyCluster | null> {
    try {
      return await this.service.updateIdeologyCluster({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          description: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: IdeologyCluster })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IdeologyCluster",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteIdeologyCluster(
    @common.Param() params: IdeologyClusterWhereUniqueInput
  ): Promise<IdeologyCluster | null> {
    try {
      return await this.service.deleteIdeologyCluster({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          description: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
