/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, MusicShare as PrismaMusicShare } from "@prisma/client";
import { LocalStorageService } from "src/storage/providers/local/local.storage.service";
import { InputJsonValue } from "src/types";
import { FileDownload, FileUpload } from "src/storage/base/storage.types";
import { LocalStorageFile } from "src/storage/providers/local/local.storage.types";

export class MusicShareServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly localStorageService: LocalStorageService
  ) {}

  async count(
    args: Omit<Prisma.MusicShareCountArgs, "select">
  ): Promise<number> {
    return this.prisma.musicShare.count(args);
  }

  async musicShares(
    args: Prisma.MusicShareFindManyArgs
  ): Promise<PrismaMusicShare[]> {
    return this.prisma.musicShare.findMany(args);
  }
  async musicShare(
    args: Prisma.MusicShareFindUniqueArgs
  ): Promise<PrismaMusicShare | null> {
    return this.prisma.musicShare.findUnique(args);
  }
  async createMusicShare(
    args: Prisma.MusicShareCreateArgs
  ): Promise<PrismaMusicShare> {
    return this.prisma.musicShare.create(args);
  }
  async updateMusicShare(
    args: Prisma.MusicShareUpdateArgs
  ): Promise<PrismaMusicShare> {
    return this.prisma.musicShare.update(args);
  }
  async deleteMusicShare(
    args: Prisma.MusicShareDeleteArgs
  ): Promise<PrismaMusicShare> {
    return this.prisma.musicShare.delete(args);
  }

  async uploadFile<T extends Prisma.MusicShareFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.MusicShareFindUniqueArgs>,
    file: FileUpload
  ): Promise<PrismaMusicShare> {
    file.filename = `profilePicture-${args.where.id}.${file.filename
      .split(".")
      .pop()}`;
    const containerPath = "file";
    const file = await this.localStorageService.uploadFile(
      file,
      [],
      1000000,
      containerPath
    );

    return await this.prisma.musicShare.update({
      where: args.where,

      data: {
        file: file as InputJsonValue,
      },
    });
  }

  async downloadFile<T extends Prisma.MusicShareFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.MusicShareFindUniqueArgs>
  ): Promise<FileDownload> {
    const { file } = await this.prisma.musicShare.findUniqueOrThrow({
      where: args.where,
    });

    return await this.localStorageService.downloadFile(
      file as unknown as LocalStorageFile
    );
  }

  async deleteFile<T extends Prisma.MusicShareFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.MusicShareFindUniqueArgs>
  ): Promise<PrismaMusicShare> {
    const { file } = await this.prisma.musicShare.findUniqueOrThrow({
      where: args.where,
    });

    await this.localStorageService.deleteFile(
      file as unknown as LocalStorageFile
    );

    return await this.prisma.musicShare.update({
      where: args.where,

      data: {
        file: Prisma.DbNull,
      },
    });
  }
}
